### PR TITLE
Smiley-Style Attributes

### PR DESCRIPTION
**Pull request by kooldev**
Implementation of PHP attributes using **Smiley-Style** `@:` notation.

### The case for `<<` and `>>` as Attribute delimiters

<table>
  <thead>
    <tr>
      <th width="50%">Advantages</th>
      <th width="50%">Disadvantages</th>
    </tr>
  </thead>
  <tbody><tr><td valign="top">
<ul>
  <li>Existing tokens (<code>T_SL</code> and <code>T_SR</code>) can be reused.</li>
  <li>Having an ending delimter makes it easier to parse parameter attributes.</li>
  <li>Attributes could be grouped within a single enclosure (<b>not</b> part of the RFC!).</li>
  <li>IDEs could auto-complete the closing delimiter (reduces overhead to 2 characters).</li>
</ul>
  </td><td valign="top">
<ul>
  <li>Existing tokens have different meaning based on context.</li>
  <li>Writing out multiple attributes inline (especially parameter attributes) is very verbose without grouping (can be solved in a future enhancement).</li>
  <li>Need to type 4 characters for attribute delimiters.</li>
  <li>Syntax is unfamiliar to most people (Hack seems to be <a href="https://github.com/facebook/hhvm/commit/3983bd2ca6b252a93d98f2bb2d7e8e89f6f004d1" target="_blank">moving away</a> from it as well).</li>
</ul>
  </td></tr></tbody>
</table>

### The case for `@:` as Attribute delimiter

<table>
  <thead>
    <tr>
      <th width="50%">Advantages</th>
      <th width="50%">Disadvantages</th>
    </tr>
  </thead>
  <tbody><tr><td valign="top">
<ul>
  <li>Only 2 characters of overhead (less verbose, especially with parameter attributes).</li>
  <li>Very easy to spot while reading PHP code because of the unique prefix.</li>
  <li>Feels more familiar to those who know Java / Python.</li>
  <li>Cannot be confused with <code>&lt;</code> and <code>&gt;</code> if PHP ever supports generics (no ambiguity in PHP's parser, but harder to read if shifts are used with attributes).</li>
</ul>
  </td><td valign="top">
<ul>
  <li>Requires a new token <code>T_ATTRIBUTE</code> that complements <code>T_DOC_COMMENT</code> (to some people this might also be an advantage depending).</li>
  <li>It is easy to forget the colon if you are used to Java annotations or Python decorators.</li>
  <li>Whitespace in attribute names is not supported (it would create ambiguity in parameter type hints due to no ending delimiter).</li>
  <li>No support for attribute grouping (not as bad due to less overhead).</li>
</ul>
  </td></tr></tbody>
</table>

## Implementation

Here is a list of things that deviate from [Attributes v2](https://wiki.php.net/rfc/attributes_v2):
- Syntax uses `@:` instead of `<<` and `>>`.
- Builtin attributes use the namespace `Attribute`.
- You have to use `Attribute\Attribute` instead of `PhpAttribute`.
- There is `Attribute\InternalAttribute` instead of `PhpCompilerAttribute`.
- Attributes do support named arguments (compatible with the [named arguments RFC](https://github.com/php/php-src/pull/5357)).
- Nested attributes are supported in all places.
- Attributes are not repeatable by default (`@:Repeatable` must be used explicitly).
- Attributes may specify valid targets using `@:Target`.
- More fine-grained target types.
- You can access count and target of an attribute using `ReflectionAttribute`.
- Registration of internal attributes uses a different API (see [zend_attributes.h](https://github.com/kooldev/php-src/blob/anno2020/Zend/zend_attributes.h)).
- There is a function called `zend_has_attribute()` to check if a specific attribute is set.
- Memory-optimized storage of marker attributes (string instead of HashTable).

You can have a look into my attempt at writing an [Attributes RFC](https://gist.github.com/kooldev/92f86e4751fc8244ad1844ac5b1036f9), it might provide some additional insights.

Attributes are supported in the following locations within PHP code:

```php
@:MyAttr
function foo() { }

@:MyAttr
class Foo
{
    @:MyAttr
    public const X = 1;

    @:MyAttr
    public $y = 2;

    @:MyAttr
    public function bar(@:MyAttr $z) { }
}

$x = new @:MyAttr class () { };
$x = @:MyAttr function () { };
$x = @:MyAttr fn () => 1;
```

Attributes are PHP classes that have an attached attribute of type `Attribute`. The classes must not be abstract and declare eighter a public constructor or no constructor at all. Arguments specified on attribute usage will be passed to the constructor in the order they are given. Type-hinting is supported, in fact you can pretend `@:` is `new` for attribute classes.

Attributes can make use of arguments that are passed to the constructor. Argument values are expressed using PHP const expressions (that you are probably familiar with from class constants or parameter default values). Attributes support these argument types:

- Scalar values (null, boolean, integer, float and string).
- Arrays (both numeric and associative).
- Constants, class constants and name resolution using `::class`.
- Nested attributes (the leading `@:` is needed to not parse them as function calls).

There are 4 builtin attributes that are needed in order to create and validate custom attributes.

```php
namespace Attribute;

@:Attribute
@:InternalAttribute
@:Target(Target::IS_CLASS)
final class Attribute { }

@:Attribute
@:InternalAttribute
@:Target(Target::IS_CLASS)
final class InternalAttribute { }

@:Attribute
@:InternalAttribute
@:Target(Target::IS_ATTRIBUTE)
final class Repeatable { }

@:Attribute
@:InternalAttribute
@:Target(Target::IS_ATTRIBUTE)
final class Target
{
    public const IS_CLASS = 1;
    public const IS_CLASS_CONSTANT = (1 << 1);
    public const IS_PROPERTY = (1 << 2);
    public const IS_FUNCTION = (1 << 3);
    public const IS_PARAMETER = (1 << 4);
    public const IS_INTERFACE = (1 << 5);
    public const IS_TRAIT = (1 << 6);
    public const IS_ATTRIBUTE = (1 << 7);
    public const IS_METHOD = (1 << 8);
    public const IS_ANONYMOUS_CLASS = (1 << 9);
    public const IS_CLOSURE = (1 << 10);
    public const IS_NESTED = (1 << 11);

    public const IS_ANY_CLASS = self::IS_CLASS | self::IS_ANONYMOUS_CLASS;
    public const IS_NAMED_TYPE = self::IS_CLASS | self::IS_INTERFACE | self::IS_TRAIT;
    public const IS_NAMED_INVOKABLE = self::IS_FUNCTION | self::IS_METHOD;
    public const IS_INVOKABLE = self::IS_NAMED_INVOKABLE  | self::IS_CLOSURE;

    public int $value;

    public function __construct(int $value);
}
```

Please have a look into the following example to see attributes in action (it is somewhat inspired by JAX-RS in Java). The only purpose of this example is to show off some cool attribute features. There is no proper documentation yet.

```php
use Attribute\{Attribute, Repeatable, Target};

@:Attribute
@:Repeatable
@:Target(Target::IS_INVOKABLE | Target::IS_ANY_CLASS)
final class Route
{
    public string $path;
    public ?string $name;

    public function __construct(string $path, ?string $name = null)
    {
        $this->path = $path;
        $this->name = $name;
    }
}

interface HttpMethod { }

@:Attribute
@:Target(Target::IS_INVOKABLE)
final class GET implements HttpMethod { }

@:Attribute
@:Target(Target::IS_INVOKABLE)
class Produces
{
    public array $types = [];
    
    public function __construct(...$types)
    {
        foreach ($types as $type) {
            $this->types[] = ($type instanceof MediaType) ? $type : new MediaType($type);
        }
    }
}

@:Attribute
@:Target(Target::IS_NESTED)
class MediaType
{
    public string $type;
    public float $q;
    
    public function __construct(string $type, float $q = 1)
    {
        $this->type = $type;
        $this->q = $q;
    }
}

@:BasicAuth
class Posts
{
    private const JSON = 'application/json', XML = 'application/xml';
    
    @:Fallback
    private const TEXT = 'text/plain';
    
    @:Inject
    @:Provides(Post::class)
    protected Repository $posts;
    
    @:GET
    @:Route('/posts/{id}', name => 'show-post')
    @:Route('/archive/post/{id}')
    @:Produces(self::JSON, self::XML, @:MediaType(self::TEXT, q => 0.4))
    public function render(@:ParamConverter('id') Post $post): array
    {
        return [];
    }
}

function dump_attr($v) {
    if ($v instanceof \ReflectionAttribute) {
        return (object)[
            'name' => $v->getName(),
            'args' => array_map('dump_attr', $v->getArguments())
        ];
    }
    
    return $v;
};

$ref = new \ReflectionClass(Posts::class);

print_r(array_map('dump_attr', $ref->getMethod('render')->getAttributes()));

$flags = \ReflectionAttribute::IS_INSTANCEOF;
$a = $ref->getMethod('render')->getAttributes(HttpMethod::class, $flags);
print_r(array_map('dump_attr', $a));
```

The reflection API is extended with the following class and methods:
```php
class ReflectionAttribute
{
    public const IS_INSTANCEOF = (1 << 1);

    public function getName(): string;
    public function getCount(): int;
    public function getTarget(): int;
    public function getArguments(): array;
    public function newInstance(): object;
}

class ReflectionClass
{
    ...
    public function getAttributes(?string $name = null, int $flags = 0): array;
}

class ReflectionFunctionAbstract
{
    ...
    public function getAttributes(?string $name = null, int $flags = 0): array;
}

class ReflectionClassConstant
{
    ...
    public function getAttributes(?string $name = null, int $flags = 0): array;
}

class ReflectionProperty
{
    ...
    public function getAttributes(?string $name = null, int $flags = 0): array;
}

class ReflectionParameter
{
    ...
    public function getAttributes(?string $name = null, int $flags = 0): array;
}
```

### CODE REVIEW

**Comment by kooldev** [comment]
You can use this dockerfile to test PHP with full support for attributes:
```dockerfile
FROM debian:buster

RUN apt-get update
RUN apt-get install -y automake autoconf libtool pkg-config make gcc bison re2c
RUN apt-get install -y libxml2-dev libssl-dev zlib1g-dev libsqlite3-dev
RUN apt-get install -y curl wget gdb

RUN mkdir /usr/local/php

WORKDIR /usr/local/php
RUN mkdir cli && mkdir php-src
RUN curl -LSs https://github.com/kooldev/php-src/archive/anno2020.tar.gz | tar -xz -C "php-src" --strip-components 1

WORKDIR /usr/local/php/php-src
RUN ./buildconf --reset

RUN ./configure \
	--disable-all \
	--enable-debug \
	--enable-cli \
	--without-pear \
	--enable-tokenizer \
	--enable-json \
	--enable-opcache
RUN make install -j4

RUN php -v
RUN php -m

CMD ["/bin/bash"]
```
Save this as `Dockerfile` in a folder of your choice than build and run it like this:
```
docker build -t php:attributes .
docker run --rm -it -v ${PWD}:/var/php php:attributes 
```
You can start with a simple test script:
```php
use Attribute\Attribute;

@:Attribute
final class MyAttribute
{
	public string $name;
	
	public function __construct(string $name)
	{
		$this->name = $name;
	}
}

$ref = new ReflectionFunction(@:MyAttribute('test') fn() => 1);

foreach ($ref->getAttributes() as $a) {
	print_r($a->getObject());
}
```
Play around with it and have some fun :-)

**Comment by nikic** [comment]
Just wondering what your plans are with regard to this. Do you plan to submit a follow-up RFC that improves on the (likely accepted) base proposal?

**Comment by kooldev** [comment]
@nikic I was planning to follow-up with an RFC proposing nested attributes and userland target / repeatable validation. As syntax will likely be `<<>>` I do not feel like implementing nested attributes as that would need to allow use of `new` in const expressions. Given the recent reaction to function calls in const expressions this might not be very promising...

Target definition and validation could still be a nice addition (probably just using arguments & class constants on `PhpAttribute`) to help with static analysis and IDE validation. Another good candidate would be grouping of attributes within a single enclosing. I played around with it two weeks ago and it should be easy to implement. Named arguments is way out of scope. I just implemented them for fun but it's good to know that it works and the structure used to store attributes can handle them without further extensions.

@beberlei Maybe we can create a follow-up RFC proposing grouping and target / repeatable validation to augment attributes right from the start?

**Comment by kooldev** [comment]
I created PRs for **Attribute Grouping** (koolkode/php-src#1) and **Userland Target Validation** (koolkode/php-src#2). Both of them are already feature complete and have a test case attached.

**Comment by beberlei** [comment]
@kooldev  just came here to check on the message from yesterday to find the two PRs, very nice!

**Comment by vanillajonathan** [comment]
The `<<` and `>>` syntax looks really ugly. The `@:` syntax looks better. But why can't it just be `@` instead of `@:` like in Java and Python, etc?

C# uses `[ExampleAttribute]` which is also nice, arguably even nicer.

**Comment by mkamranpk** [comment]
Nice work on Attributes! Just a little feedback from a Developer if I may: I would highly recommend going with the @: syntax as you have done so in this PR.

It's not a perfect world, and therefore, only a select few get to vote on what syntax goes forward, and I see the majority of that select group has voted for the <<>> syntax. My feeling as a developer tells me that the @: syntax is more approachable for most people.

The advantages you list for the @: syntax are spot on in the PR! 

In the disadvantages, you mention: "Whitespace in attribute names is not supported (it would create ambiguity in parameter type hints due to no ending delimiter)." - This is actually a good design decision / rule. We should not be allowing whitespace in it.

Regarding the other disadvantage: "It is easy to forget the colon if you are used to Java annotations or Python decorators." - Probably overthinking it, it won't be much of an issue, especially with modern IDEs.

Thanks and best wishes!

**Comment by beberlei** [comment]
@mkamranpk The choice of `<<Attr>>` as syntax has been voted on.

**Comment by g13013** [comment]
@beberlei could this choice be reconsidered ?

**Comment by beberlei** [comment]
@g13013 yes always, but it is unlikely, bacause the vote included a secondary vote to pick smiley or <<>> syntax already. 

Someone needs to propose an RFC before 8.0, the deadline is mid/end of June.

**Comment by g13013** [comment]
@beberlei excuse me but, I don't find any reason someone could prefer `<<>>` over `@:` as I find the latest much much readable, and believe its the case of the majority of the developers out there.

I believe, at most this syntax would pollute future implementation and with time would become a bad practice using them in PHP.

**Comment by jdreesen** [comment]
So, why don't you propose an RFC? Maybe you can convince everyone with your arguments.

**Comment by g13013** [comment]
anyways, thanks for reading.

**Comment by beberlei** [comment]
Yes, thats the way PHP works at the language level. The time to argue for changes to proposed features is during the RFC discussion and voting phases. Working on an RFC of this magnitude takes months of work, the vote sets many things into stone, so that discussion is ended at some point and maintainers and contributors get reliability.

**Comment by allan-simon** [comment]
sorry if I put this comment here and it's not the right place

How is multiline handled
i.e can I write
```
    <<Assert\Range(["min" => 120, "max" => 180, "minMessage" => "You must be at least {{ limit }}cm tall to enter"])>>
```

as 

```
<<Assert\Range([
   "min" => 120,
   "max" => 180,
   "minMessage" =>   "You must be at least {{ limit }}cm tall to enter"
])>>
```

?

(the rfc put multiline comment-style annotation but always single line new-style annotation, so I'm a bit scared ^^ )

**Comment by theodorejb** [comment]
@allan-simon Yes, you can write that. If the [Shorter Attribute Syntax RFC](https://wiki.php.net/rfc/shorter_attribute_syntax) is accepted, you would write it like this instead:

```php
@@Assert\Range([
   "min" => 120,
   "max" => 180,
   "minMessage" => "You must be at least {{ limit }}cm tall to enter",
])
```
or
```js
#[Assert\Range([
   "min" => 120,
   "max" => 180,
   "minMessage" => "You must be at least {{ limit }}cm tall to enter",
])]
```
Personally I prefer the `@@` syntax since the BC break is smaller and it's slightly less verbose.

**Comment by allan-simon** [comment]
great , thanks for the very quick answer, I have to admit I would also prefer the `@@` syntax as it's the closest to the current annotation-in-comment.

**Pull request closed without merging**
