### PR TITLE
Annotations

### PR DESCRIPTION
**Pull request by kooldev**
Annotation system for PHP, parsed along with source files and persisted in Opcache. Example usage of annotations:

```php
@:BasicAuth
class Posts
{
    private const JSON = 'application/json', XML = 'application/xml';

    @:Fallback
    private const TEXT = 'text/plain';

    @:Inject
    @:Provides(Post::class)
    protected Repository $posts;

    @:GET
    @:Route('/posts/{id}', name = 'show-post')
    @:Route('/archive/post/{id}')
    @:Produces(self::JSON, self::XML, @:MediaType(self::TEXT, q = 0.4))
    public function render(@:ParamConverter('id') Post $post): array
    {
        return [];
    }
}

$ref = new \ReflectionClass(Posts::class);

foreach ($ref->getMethodsAnnotatedWith(Route::class) as $method) {
    print_r($method->getAnnotationObjects(Route::class));
}
```
The reflection API is enhanced with additional methods to retrieve and filter by annotations:
```php
class ReflectionClass
{
    public function isAnnotatedWith(string $filter, bool $inherited = false): array;
    public function getAnnotationTypes(): array;
    public function getAnnotationObjects(?string $filter = null, bool $inherited = false): array;
}

class ReflectionClassConstant
{
    public function isAnnotatedWith(string $filter, bool $inherited = false): array;
    public function getAnnotationTypes(): array;
    public function getAnnotationObjects(?string $filter = null, bool $inherited = false): array;
}

class ReflectionFunctionAbstract
{
    public function isAnnotatedWith(string $filter, bool $inherited = false): array;
    public function getAnnotationTypes(): array;
    public function getAnnotationObjects(?string $filter = null, bool $inherited = false): array;
    public function getConstantsAnnotatedWith(string $filter, bool $inherited = false): array;
    public function getPropertiesAnnotatedWith(string $filter, bool $inherited = false): array;
    public function getMethodsAnnotatedWith(string $filter, bool $inherited = false): array;
    public function getMethodsWithAnnotatedParameter(string $filter, bool $inherited = false): array;
}

class ReflectionParameter
{
    public function isAnnotatedWith(string $filter, bool $inherited = false): array;
    public function getAnnotationTypes(): array;
    public function getAnnotationObjects(?string $filter = null, bool $inherited = false): array;
}

class ReflectionProperty
{
    public function isAnnotatedWith(string $filter, bool $inherited = false): array;
    public function getAnnotationTypes(): array;
    public function getAnnotationObjects(?string $filter = null, bool $inherited = false): array;
}
```

- [x] Introduce lexer token for annotations.
- [x] Extend PHP grammar (functions, types, class constants, properties, methods & parameters).
- [x] Parse annotations into an AST.
- [x] Implement annotations in code dump (AST export).
- [x] Attach parsed annotation data to source elements.
- [x] Persist annotation data in opcache (memory & files).
- [x] Retrieve annotation objects using reflection.
- [x] Filter annotations objects with support for inheritance.
- [x] Support multiple annotations of the same type on each element.
- [x] Add test cases.

Things that could be implemented in addition:
- Consider adding builtin annotations: @:Annotation, @:Target, @:Required, @:Jit, ...

- Look into lazy-loading annotations from opcache. The basic idea would be to load only the outermost `HashTable` wit the string keys to be able to check for annotations by name. All values should use zvals of type `IS_PTR` to refer to opcache memory that holds the annotation data. Upon first access the data is loaded from opcache and the value in the map is replaced with the actual value.

### CODE REVIEW

**Comment by kooldev** [comment]
Hi @beberlei, I was working on adding annotations to PHP for a while and decided to take it to GitHub now that you brought it up again as `[RFC] Attributes v2`. Since you are the author of that RFC I want to share this with you before anyone else. I think by now I have addressed pretty much everything on your open issues list (an maybe even a little more than that).

- Annotations use `@:` instead of `<<` and `>>` which makes them a little easier to recognize and read. Due to no ending delimter being used annotation names must not contain any whitespace (namespace separators are of cource allowed). This requires a new lexer token of type `T_ANNOTATION` to avoid ambiguity in the parser when parameters are annotated.

- Namespaces (and aliases) are fully supported, `@:Foo`, `@:\Foo`, and ` @:Bar\Foo` can be used and PHP's default name resolution rules apply.

- Annotation may specify no data `@:Foo` / `@:Foo()`, an ordered list of constructor arguments `@:Foo(1, 2, 3)`, named parameters that are mapped to public properties `@:Foo(message = 'Hello', ttl = 1800)` or a combination of these where constructor arguments have to be specified first `@:Route('/show', name = 'show-all')`.

- Supported values for args / params are `null`, `true`, `false`, integers, floats, string literals, constants, class constants, arrays and nested annotations. Arrays use shorthand notation `[ 1, 2, 3 ]` only, associative arrays make use of the double arrow as in PHP `[ 'key' => 'test', 'ttl' => 300 ]`. Nested annotations can be used like any other value, the `@:` prefix is mandatory to not confuse them with function calls `@:Formats(@:Type('json'), @:Type('xml', q = .5))`.

- Constants and class constants are related to the location where the annotation is placed. They take this scope into account. For example a class annotation may refer to a value of a private class constant in an annotation `@:MediaType(self::TYPE) class Foo { private const FOO = 'a/b' }`. Support for `self::` avoids the need to repeat the class name here. Support for class name lookup`Repository::class` is implemented, this includes using `self::class` to refer to the annotated class.

- Access via Reflection API takes your suggestion of being able to filter annotations on read using an `instanceof` condition into account. You could retrieve all Doctrine annotations using `$ref->getAnnotationObjects(Doctrine\Annotation::class)` assuming `Annotation` is the common base class of all Doctrine annotations.

I still need to adjust some things in the code and implement classes `ReflectionAnnotation` and `ReflectionAnnotationExpression` to properly expose annotations without creating the objects (i am using `stdClass` for now to wrap data when calling `getAnnotations()`. I also need to add a ton of test cases for this feature, right now i am using a bunch of scripts to try things out, but they are not `phpt` file...

What do you think about this? Could this PR become the new base of `[RFC] Attributes v2` and would you be interested in joining forces? I have no experience with the RFC process yet...

**Comment by beberlei** [comment]
@kooldev will reply within the week

**Comment by kooldev** [comment]
Another nice feature that could be added is single-expression closures (arrow function) as attribute / param values. They could be compiled into a `Closure` and injected into the annotation when an object is created. This would enable things like Design-By-Contract, something like this:

```php
interface Test
{
    @:Precondition({ $a > 0 }, message = 'Argument must not be negative')
    public function doSomething(int $a);
}
```

Supporting this syntax is trivial, only a production `annotation_expr: '{' expr '}'` has to be added to fully support an arbitrary PHP expression as value. Compiling and using the expression will be more difficult but should boil down to reusing how `fn ()` is compiled. This would also require auto-generating the function argument definition from context and it should support `self`, `static` and `$this` when used on a class-based element. This is perhaps something for another RFC / PR with great potential in the future.

**Comment by kooldev** [comment]
@beberlei I am pretty much finished with everything on my agenda and would like to move ahead... Have you had a chance to try it out yet?

**Comment by kooldev** [comment]
Hi @brzuchal, I implemented PHP annotations in this PR in a way that is very similar to what you proposed in [RFC: Annotations 2.0](https://wiki.php.net/rfc/annotations_v2) last year. Are you still interested in this?

As you can see i also invited Benjamin Eberlei because he is the author of [RFC: Attributes v2](https://wiki.php.net/rfc/attributes_v2) that covers the same topic. Maybe all of the work you have done so far could be merged into a single RFC backed by the three of us to finally make some progress and see if people are interested in bringing this to PHP8.

This is what i used to compile PHP with annotations after checkout:
```
./buildconf --reset
./configure \
	--disable-all \
	--enable-debug \
	--enable-cli \
	--disable-cgi \
	--disable-phpdbg \
	--without-pear \
	--enable-opcache \
	--enable-tokenizer
make install -j4
```

**Comment by beberlei** [comment]
@kooldev Sorry that I didn't reply earlier, but the current world situation has me on edge a little with other things to do.

I don't want to dampen your enthusiasm here, because the patch looks awesome, but attributes is a highly political topic among voters, and I designed my RFC around the politics first, and not around what is technically possible. I want a more comprehensive solution myself in some areas, but the chance of passing is 0 after interviewing a large amount of internals contributors and voters.

Even my proposal currently looks to have a chance at only barely passing, but your patch has much more code and introduces @ as a symbol, where I chose carefully to reuse the `<<>>` after interviewing core committers what is possible (meaning, what they would vote +1 on). 

I believe my choice of allowing only constant AST expressions in attributes is a defensive approach here, especially since that reduces the implementation code significantly and given the [recent discussions](https://externals.io/message/108630) around allowing more choice was [voted down with a significant margin](https://wiki.php.net/rfc/calls_in_constant_expressions_poll). And if discussions about constant expression improvements pass in the future, then AttSorributes would benefit automatically.

There are two large topics that I want to address in my RFC in the next phase:

- Allow multiple attributes of the same type
- Find a way of distinction of internal attributes vs userland, because internals should be validated strictly at compile time and userland only at "Reflection time". This was the result of discussions with several core contributors.

I wouldn't want to change much more than that (and other small feedback) in my RFC before going to vote. Especially the syntax is going to stay `<<>>` and arguments are going to be constant AST only.

**Comment by kooldev** [comment]
I could change delimiters to `<<` and `>>` with very little effort (just removing the token from the lexer and adjust the production for `annotation` is sufficient) but i am sure this is not the primary concern you have with this.

> I believe my choice of allowing only constant AST expressions in attributes is a defensive approach here, [...]

I agree with this and (even though it might not look like it) support an even smaller set of expressions (no operations like addition for example). It is just primitive types, constants, arrays and nested annotations. It is reusing PHP's routines for primitives, constants and the AST construction for arrays (that you support as well). Nested annotations are as simple as arrays in their implementation but they do allow for improved type-hinting. There are no non-constant elements at work here (except for constant value lookup, but this should also be the case with your implementation of attributes) because this would not work with opcache.

Once you have finalized your PR (and maybe added support for attributes on function / method parameters) you will end up with almost the same amount of code (and in many places even the exact same code) for the basic features. I took this a little further by extending reflection for better usability and added the annotation filtering feature. These things account for most of the additional code lines.

Once you support multiple attributes of the same type and start doing the inheritance-based filtering of attributes you will end up with most of the code that I have written in `zend_annotations.c` and the difference in number of changes will shrink to the diff in reflection APIs. As soon as you implement `ReflectionAttribute::getAsObject()` you will end up with another chunk of code from that file and the gap in number of code lines will close...

I thought it would be less lines of code as I staret out, but C code is quite wordy when it comes to these things. ;-)

**Comment by brzuchal** [comment]
@kooldev the effort you took is impressive although currently I'm highly occupied on finishing project and taking up a subject like annotations is not a trivial task.

I do like the `@` for an annotation prefix and prefer that over `<<` and `>>` but these probably have bigger chance to get into the language (too bad it's gonna stay like that for ages then). I agree with @beberlei that it's more like political choice and I'll support Attributes RFC.

One thing I see really nice and I don't know @beberlei how much effort it would take to add is the nesting of attributes just like @kooldev did in his proposal.

**Comment by beberlei** [comment]
@brzuchal nested attributes is not a good idea in my opinion, because it blocks the path for future improvements based on constant AST changes.

**Comment by kooldev** [comment]
I think nested attributes would be very nice to habe as they allow to avoid falling back to that "everything is an array" style that PHP is well known for. There is a way to have both the power of constant AST and nested attributes at the same time and it is very simple to achieve. All we have to do is to define attribute arguments in the grammar like this: `expr | attribute`. 
```php
<<A1(1 + 2, <<A2(3 + 4)>>)>>
function foo() { }

@:A1(1 + 2, @:A2(3 + 4))
function foo() { }
```
Every argument is eighter a zval / const expression or a nested attribute. The C code needed to make this work is just a few lines to check arguments and recursively call the import function. This would however not allow us to define a list (array) of attributes. Const expressions allow for arrays, but attributes cannot be an element of such an array.

**Comment by beberlei** [comment]
@kooldev this would make it inconsistent imho, if it would only work as argument, but not inside an array that is an argument. We shouldn't add stuff that is even more controversial than the feature itself is. Imho you can just make everything a top level attribute if you need "nesting".

```php
/** @JoinTable(name="foo", joinColumns={@JoinColumn(name="id"), @JoinColumn("id")}) */
```

becomes:

```php
<<JoinTable("foo")>>
<<JoinColumn("id")>>
<<JoinColumn("id2)>>
```

**Comment by kooldev** [comment]
@beberlei Or even use varargs like this:
```php
<<JoinTable("foo")>>
<<JoinColumns("id", "id2")>>
```
I just created beberlei/php-src#5 that supports this. ;-)

**Pull request closed without merging**
